
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 34
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 * Given that the standard has decreed that size_t exists since 1989,
 * I guess we can afford to depend on it. Manoj.
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 29
#define YY_END_OF_BUFFER 30
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[237] =
    {   0,
        0,    0,   30,   28,   27,   29,   26,   28,    1,    6,
       28,    7,   28,    8,    5,    9,   28,   11,   28,   28,
       28,   28,   28,   28,    4,    3,   28,   28,    2,   28,
       28,    3,   28,   28,   28,    1,    0,    0,    0,   18,
       19,    0,   20,   17,   21,    0,   23,    0,    0,    0,
        0,    0,    0,   16,   15,    0,    0,   14,    0,    0,
        0,    0,    0,   10,   12,    0,   15,    0,    0,    0,
        0,   14,    0,    0,    0,    0,    0,    0,    0,    0,
        2,    0,   14,    0,    0,    0,    0,    0,    0,    3,
        1,    0,    1,    0,    0,   22,   24,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   14,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   12,    8,    0,    0,    0,    0,    0,
        0,    0,    7,    0,    0,    3,    0,   13,    0,    0,
        0,    0,    4,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   25,    0,
        0,    0,    0,   16,    0,    0,    0,    0,    0,    9,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    4,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   16,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    5,    1,    5,    6,    4,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    1,    1,    1,
        1,    1,    1,    1,    8,    1,    1,    1,    9,    1,
       10,   11,    1,   12,   13,    1,   14,   15,    1,   16,
        1,    1,    1,   17,   18,    1,   19,    1,   20,   21,
        1,    1,    1,    4,    1,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,
       35,   36,    1,   37,   38,   39,   40,    1,   41,    1,
       42,   43,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[44] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[237] =
    {   0,
        0,    0,  331,  332,  332,  332,  332,  323,   38,  290,
       57,    0,  285,  332,  332,  332,  305,  332,   12,  304,
       26,   32,  288,   27,  302,    0,  289,  280,   67,  281,
       53,  332,  285,  293,  281,   97,  310,   50,  302,  276,
      332,  271,  332,  332,  332,  291,  332,   22,  290,   79,
       85,  274,   82,  288,  332,  275,  266,   80,  267,   56,
      271,  279,  267,  332,   80,  275,  263,   87,  264,   92,
       29,  105,   94,   97,  105,  272,  111,  106,  267,  274,
      332,  113,  133,  117,  263,  116,  256,  261,  268,  332,
      149,  286,  285,  269,  276,  332,  332,  261,  249,  254,

      249,  253,  250,  272,  240,  257,  246,  251,  252,  124,
      245,  252,  332,  128,  264,  133,  240,  236,  232,  237,
      244,  231,  231,  332,  332,  228,  238,  243,  238,  224,
      223,  222,  332,  231,   45,  235,  230,  332,  218,  232,
      217,  220,  219,  221,  233,  228,  211,  211,  208,  218,
      223,  218,  204,  203,  202,  211,  138,  211,  332,  199,
      213,  198,  201,  200,  202,  193,  213,  190,  204,  332,
      194,  201,  197,  199,  198,  147,  197,  188,  203,  181,
      201,  178,  192,  182,  189,  185,  187,  186,  186,  184,
      172,  174,  170,  180,  175,  170,  332,  179,  172,  167,

      163,  165,  161,  171,  166,  161,  332,  170,  158,  162,
      149,  162,  155,  149,  157,  151,  155,  142,  155,  148,
      148,  141,  150,  148,  138,  143,  135,  144,  139,  113,
       89,   86,   69,   61,   16,  332
    } ;

static yyconst flex_int16_t yy_def[237] =
    {   0,
      236,    1,  236,  236,  236,  236,  236,  236,  236,  236,
      236,   11,  236,  236,  236,  236,   11,  236,   11,  236,
       11,   11,   11,   11,  236,   11,  236,  236,   11,  236,
       11,  236,  236,  236,   11,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,

      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,

      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,    0
    } ;

static yyconst flex_int16_t yy_nxt[376] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   12,
       13,   14,   15,   11,   16,   17,   11,    4,   18,   11,
       11,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       11,   28,   29,   11,   30,   31,    4,   32,   33,   11,
       34,   35,   11,   37,   36,   66,   38,   70,   55,   67,
       68,   71,   77,   73,   92,   98,   93,   74,   72,   99,
      100,   78,  126,   38,   40,  108,   41,   42,   43,   44,
       81,   45,   46,   75,   86,   47,  172,  118,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   87,   57,   58,
      119,   59,   60,   90,   55,   61,   82,   62,   63,   83,

      102,   84,   37,   36,  103,   38,  105,  109,  235,  114,
      106,  104,  115,   98,  116,  127,  110,   99,  100,  124,
      128,  120,   38,  125,   55,   98,  107,   98,  234,   99,
      100,   99,  100,  108,  114,   90,  130,  115,  129,  116,
      131,   55,  132,  137,  135,  117,  136,  108,  138,   98,
      139,   90,  141,   99,  100,   91,  117,   38,  154,  157,
      155,   55,  114,  113,  159,  115,  160,  116,  233,  185,
      187,  197,  232,  113,   38,  113,  207,  231,  230,   81,
       81,  229,  228,   55,  227,  226,  225,  197,  224,  223,
       90,  222,  221,  113,  220,  219,   55,  218,  217,  216,

      215,  214,   81,  213,  212,   90,  211,  210,  209,  207,
      207,  208,  207,   55,  206,  205,  204,  203,  202,  201,
      200,  199,  197,  198,  197,   90,  196,  195,  194,  193,
      192,  191,   55,  190,  189,  188,  187,  186,   97,  113,
      184,  113,  113,   45,  183,   97,  182,  181,  180,  179,
      178,   90,  177,  176,  175,  174,  173,  124,  156,   81,
      171,   81,   81,  170,  169,  124,  168,  167,  166,  165,
      164,  163,  162,  161,  158,  156,   41,  153,   43,  152,
      151,   55,  150,  149,   43,   97,   97,  148,  147,  146,
      145,   93,   93,  144,  143,  142,  140,  134,  133,  125,

      124,  123,  122,   55,  121,  120,  117,  113,  112,  111,
      108,  101,   97,   96,   95,   94,   91,   90,   89,   88,
       85,   81,   80,   79,   76,   69,   65,   64,   39,   36,
      236,    3,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236
    } ;

static yyconst flex_int16_t yy_chk[376] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    9,    9,   19,    9,   21,  235,   19,
       19,   21,   24,   22,   38,   48,   38,   22,   21,   48,
       48,   24,   71,    9,   11,   71,   11,   11,   11,   11,
      135,   11,   11,   22,   31,   11,  135,   60,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   31,   11,   11,
       60,   11,   11,  234,   11,   11,   29,   11,   11,   29,

       50,   29,   36,   36,   50,   36,   51,   53,  233,   58,
       51,   50,   58,   65,   58,   72,   53,   65,   65,   68,
       74,   68,   36,   70,  232,   70,   51,   73,  231,   70,
       70,   73,   73,   74,   72,   73,   77,   72,   75,   72,
       78,   75,   78,   83,   82,   78,   82,   77,   84,   86,
       84,  230,   86,   86,   86,   91,   84,   91,  110,  114,
      110,  114,   83,  157,  116,   83,  116,   83,  229,  157,
      176,  176,  228,  227,   91,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  206,  205,  204,  203,  202,  201,

      200,  199,  198,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  175,  174,  173,  172,  171,  169,  168,
      167,  166,  165,  164,  163,  162,  161,  160,  158,  156,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  141,  140,  139,  137,  136,  134,
      132,  131,  130,  129,  128,  127,  126,  123,  122,  121,
      120,  119,  118,  117,  115,  112,  111,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   95,
       94,   93,   92,   89,   88,   87,   85,   80,   79,   76,

       69,   67,   66,   63,   62,   61,   59,   57,   56,   54,
       52,   49,   46,   42,   40,   39,   37,   35,   34,   33,
       30,   28,   27,   25,   23,   20,   17,   13,   10,    8,
        3,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  236,  236
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "u.l"
#line 3 "u.l"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "u.h"
#include "u.tab.h"

//#define DEBUG_UNIT_PARSER

extern uyyType theOutput;

double preVal( char* yytext, int yylen );
double lenVal( char* yytext, int yylen );
double timVal( char* yytext, int yylen );
double masVal( char* yytext, int yylen );
double temVal( char* yytext, int yylen );
double curVal( char* yytext, int yylen );
double accVal( char* yytext, int yylen );
double eneVal( char* yytext, int yylen );
double forVal( char* yytext, int yylen );
double freVal( char* yytext, int yylen );
double powVal( char* yytext, int yylen );
double prsVal( char* yytext, int yylen );
double molVal( char* yytext, int yylen );
/* Prefix  Symbol  Value
------  ------  -----
yotta    Y      1e+24
zetta    Z      1e+21
exa      E      1e+18
peta     P      1e+15
tera     T      1e+12
giga     G      1e+09 
mega     M      1e+06 
kilo     k      1e+03 
hecto    h      1e+02 
deca     e      1e+01 
deci     d      1e−01
centi    c      1e−02
milli    m      1e−03 
micro    u      1e−06 
nano     n      1e−09 
pico     p      1e−12 
femto    f      1e−15 
atto     a      1e−18 
zepto    z      1e−21 
yocto    y      1e−24 
*/
/* Length_units  Symbol    conversion_to_SI
------------  ------    ----------------
meter         m         1.0   
angstrom      angstrom  1e-10
astron.unit   astrUnit 149597870690
feet          feet      0.3048
foot          foot      0.3048
inch          inch      0.0254     
mile          mile      1609.344
light year    ly        9454254955500000
parsec        parsec    30856774879000000
*/
/* Time_units    Symbol     conversion_to_SI
------------  ------     ----------------
seconds        s                     1
minute         min                  60
hour           h                  3600
day            day               86400 
week           week             604800
fortnight      fortnight       1209600
month          month           2628000
year           yr             31536000
decade         decade        315360000
century        century      3153600000
millennium     millennium  31536000000
*/
/* Mass_units     Symbol     conversion_to_SI
-------------  ---------  ----------------
gram           g          1e-3
atomic mass u. AtMaUnit   1.66053873e-27
ounce          ounce      0.028349523125 
pound          pound      0.45359237
ton            ton        1000.0
tonne          tonne      1000.0     
*/
/* Temp_units     Symbol     conversion_to_SI
-------------  ---------  ----------------
kelvin         K          1.0
*/
/* Electric_
current_units  Symbol     conversion_to_SI
-------------  ---------  ----------------
Ampere           A          1.0
*/
/* Acceleration_units  Symbol  conversion_to_SI
------------------  ------  ----------------
g-unit              G   9.80665
gal                 gal     0.01
*/
/* Energy_units        Symbol  conversion_to_SI
------------------  ------  ----------------
Joule               J       1.0
calorie             cal     4.184
erg                 erg     1e-7     
*/
/* Force_units         Symbol  conversion_to_SI
------------------  ------  ----------------
Newton              N       1.0
dyne                dyne    0.00001     
*/
/* Frequency_units     Symbol  conversion_to_SI
------------------  ------  ----------------
Hertz               Hz      1.0     
*/
/* Power_units         Symbol  conversion_to_SI
------------------  ------  ----------------
Watt                W       1.0
*/
/* Pressure_units      Symbol  conversion_to_SI
------------------  ------  ----------------
Pascal              Pa           1.0
atmosphere          atm     101325.01
bar                 bar     100000.0
cm of hg            cmHg      1333.2239
mm of hg            mmHg       133.32239     
*/
/* Amount_subs_units   Symbol  conversion_to_SI
------------------  ------  ----------------
mole                mol     1.0
*/
#line 742 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 188 "u.l"


#line 898 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 237 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 332 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 190 "u.l"
{ 
              yylval.c = atof(yytext); 
              return TOKEN_NUMBER; 
            }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 195 "u.l"
{ 
              yylval.pl = 1;
              yylval.pm = 0; 
              yylval.pt = 0; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = lenVal( yytext, yyleng );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 205 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = 1; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = timVal( yytext, yyleng );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 215 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 1; 
              yylval.pt = 0; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = masVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 225 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = 0; 
              yylval.pT = 1; 
              yylval.pA = 0; 
              yylval.c = temVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 235 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = 0; 
              yylval.pT = 0; 
              yylval.pA = 1; 
              yylval.c = curVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 245 "u.l"
{ 
              yylval.pl = 1;
              yylval.pm = 0; 
              yylval.pt = -2; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = accVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 255 "u.l"
{ 
              yylval.pl = 2;
              yylval.pm = 1; 
              yylval.pt = -2; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = eneVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 265 "u.l"
{ 
              yylval.pl = 1;
              yylval.pm = 1; 
              yylval.pt = -2; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = forVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 275 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = -1; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = freVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 285 "u.l"
{ 
              yylval.pl = 2;
              yylval.pm = 1; 
              yylval.pt = -3; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = powVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 295 "u.l"
{ 
              yylval.pl = -1;
              yylval.pm = 1; 
              yylval.pt = -2; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = prsVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 305 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = 0; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = molVal( yytext, yyleng ); 
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 315 "u.l"
{ 
              yylval.pl = 1;
              yylval.pm = 0; 
              yylval.pt = 0; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= lenVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 326 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = 1; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= timVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 337 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 1; 
              yylval.pt = 0; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= masVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 348 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = 0; 
              yylval.pT = 1; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= temVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 359 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = 0; 
              yylval.pT = 0; 
              yylval.pA = 1; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= curVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 370 "u.l"
{ 
              yylval.pl = 1;
              yylval.pm = 0; 
              yylval.pt = -2; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= accVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 381 "u.l"
{ 
              yylval.pl = 2;
              yylval.pm = 1; 
              yylval.pt = -2; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= eneVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 392 "u.l"
{ 
              yylval.pl = 1;
              yylval.pm = 1; 
              yylval.pt = -2; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= forVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 403 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = -1; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= freVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 414 "u.l"
{ 
              yylval.pl = 2;
              yylval.pm = 1; 
              yylval.pt = -3; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= powVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 425 "u.l"
{ 
              yylval.pl = -1;
              yylval.pm = 1; 
              yylval.pt = -2; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= prsVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 436 "u.l"
{ 
              yylval.pl = 0;
              yylval.pm = 0; 
              yylval.pt = 0; 
              yylval.pT = 0; 
              yylval.pA = 0; 
              yylval.c = preVal( yytext, yyleng );
              yylval.c *= molVal( yytext+1, yyleng-1 );
              return TOKEN_UNIT; 
            }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 448 "u.l"
{ return *yytext; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 450 "u.l"
; /* skip whitespace */
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 452 "u.l"
yyerror( "invalid character" );
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 454 "u.l"
ECHO;
	YY_BREAK
#line 1333 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 237 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 237 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 236);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 454 "u.l"



int yywrap(void) {  return 1; } 

double preVal( char* yytext, int yylen ) {
  double p = 1;
  if( yylen > 1 ) {
     switch( yytext[0] ) {
       case 'Y': p = 1e+24; break;
       case 'Z': p = 1e+21; break;
       case 'E': p = 1e+18; break;
       case 'P': p = 1e+15; break;
       case 'T': p = 1e+12; break;
       case 'G': p = 1e+09; break;
       case 'M': p = 1e+06; break;
       case 'k': p = 1e+03; break;
       case 'h': p = 1e+02; break;
       case 'e': p = 1e+01; break;
       case 'd': p = 1e-01; break;
       case 'c': p = 1e-02; break;
       case 'm': p = 1e-03; break;
       case 'u': p = 1e-06; break;
       case 'n': p = 1e-09; break;
       case 'p': p = 1e-12; break;
       case 'f': p = 1e-15; break;
       case 'a': p = 1e-18; break;
       case 'z': p = 1e-21; break;
       case 'y': p = 1e-24; break;
     }
  }
#ifdef DEBUG_UNIT_PARSER
  printf("prefix %c value: %g\n", yytext[0], p );
#endif
  return p;
}

double lenVal( char* yytext, int yylen ) {
  double l = 1;
  if( strcmp( yytext, "m" ) == 0 )               l = 1.0;
  else if( strcmp( yytext, "angstrom" ) == 0 )   l = 1e-10;
  else if( strcmp( yytext, "astrUnit" ) == 0 )   l = 149597870690.0;
  else if( strcmp( yytext, "feet" ) == 0 )       l = 0.3048;
  else if( strcmp( yytext, "foot" ) == 0 )       l = 0.3048;
  else if( strcmp( yytext, "inch" ) == 0 )       l = 0.0254;
  else if( strcmp( yytext, "mile" ) == 0 )       l = 1609.344;
  else if( strcmp( yytext, "ly" ) == 0 )         l = 9454254955500000.0;
  else if( strcmp( yytext, "parsec" ) == 0 )     l = 30856774879000000.0;
#ifdef DEBUG_UNIT_PARSER
  printf("length %s value: %g\n", yytext, l );
#endif
  return l;
}


double timVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "s" ) == 0 )               t = 1.0;
  else if( strcmp( yytext, "min" ) == 0 )        t = 60.0;
  else if( strcmp( yytext, "h" ) == 0 )          t = 3600.0;
  else if( strcmp( yytext, "day" ) == 0 )        t = 86400.0;
  else if( strcmp( yytext, "week" ) == 0 )       t = 604800.0;
  else if( strcmp( yytext, "fortnight" ) == 0 )  t = 1209600.0;
  else if( strcmp( yytext, "month" ) == 0 )      t = 2628000.0;
  else if( strcmp( yytext, "yr" ) == 0 )         t = 31536000.0;
  else if( strcmp( yytext, "decade" ) == 0 )     t = 315360000.0;
  else if( strcmp( yytext, "century" ) == 0 )    t = 3153600000.0;
  else if( strcmp( yytext, "millennium" ) == 0 ) t = 31536000000.0;
#ifdef DEBUG_UNIT_PARSER
  printf("time %s value: %g\n", yytext, t );
#endif
  return t;
}

double masVal( char* yytext, int yylen ) {
  double m = 1.0;
  if( strcmp( yytext, "g" ) == 0 )               m = 1.0e-3;
  else if( strcmp( yytext, "AtMaUnit" ) == 0 )   m = 1.66053873e-27;
  else if( strcmp( yytext, "ounce" ) == 0 )      m = 0.028349523125;
  else if( strcmp( yytext, "pound" ) == 0 )      m = 0.45359237;
  else if( strcmp( yytext, "ton" ) == 0 )        m = 1000.0;
  else if( strcmp( yytext, "tonne" ) == 0 )      m = 1000.0;
#ifdef DEBUG_UNIT_PARSER
  printf("mass %s value: %g\n", yytext, m );
#endif
  return m;
}

double temVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "K" ) == 0 )               t = 1.0;
#ifdef DEBUG_UNIT_PARSER
  printf("temp %s value: %g\n", yytext, t );
#endif
  return t;
}

double curVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "A" ) == 0 )               t = 1.0;
#ifdef DEBUG_UNIT_PARSER
  printf("e.c. %s value: %g\n", yytext, t );
#endif
  return t;
}

double accVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "G" ) == 0 )               t = 9.80665;
  else if( strcmp( yytext, "gal" ) == 0 )        t = 0.01;
#ifdef DEBUG_UNIT_PARSER
  printf("acc. %s value: %g\n", yytext, t );
#endif
  return t;
}

double eneVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "J" ) == 0 )               t = 1.0;
  else if( strcmp( yytext, "cal" ) == 0 )        t = 4.184;
  else if( strcmp( yytext, "erg" ) == 0 )        t = 1e-7;
#ifdef DEBUG_UNIT_PARSER
  printf("ener %s value: %g\n", yytext, t );
#endif
  return t;
}

double forVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "N" ) == 0 )               t = 1.0;
  else if( strcmp( yytext, "dyne" ) == 0 )       t = 0.00001;
#ifdef DEBUG_UNIT_PARSER
  printf("forc %s value: %g\n", yytext, t );
#endif
  return t;
}

double freVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "Hz" ) == 0 )              t = 1.0;
#ifdef DEBUG_UNIT_PARSER
  printf("freq %s value: %g\n", yytext, t );
#endif
  return t;
}

double powVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "W" ) == 0 )              t = 1.0;
#ifdef DEBUG_UNIT_PARSER
  printf("pow. %s value: %g\n", yytext, t );
#endif
  return t;
}

double prsVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "Pa" ) == 0 )              t = 1.0;
  else if( strcmp( yytext, "atm" ) == 0 )        t = 101325.01;
  else if( strcmp( yytext, "bar" ) == 0 )        t = 100000.0;
  else if( strcmp( yytext, "cmHg" ) == 0 )       t = 1333.2239;
  else if( strcmp( yytext, "mmHg" ) == 0 )       t = 133.32239;
#ifdef DEBUG_UNIT_PARSER
  printf("press %s value: %g\n", yytext, t );
#endif
  return t;
}

double molVal( char* yytext, int yylen ) {
  double t = 1.0;
  if( strcmp( yytext, "mol" ) == 0 )              t = 1.0;
#ifdef DEBUG_UNIT_PARSER
  printf("a.s. %s value: %g\n", yytext, t );
#endif
  return t;
}


/* int main() */
int myParser( char* buff, uyyType* out )
{
  YY_BUFFER_STATE str_buffer = NULL;
  int err;

  /* printf("main: scaning buf:\n%s\nOutput:",buff); */

  str_buffer = yy_scan_string(buff );
  err = yyparse();

  out[0] = theOutput;

/*  printf("err: %i\n",err);
  printf( "\n\tleng: %f\n\tmass: %f\n\ttime: %f\n\ttemp: %f\n\tcurr: %f\n\ttoSI: %g\n", 
			 theOutput.pl, theOutput.pm, theOutput.pt, theOutput.pT, theOutput.pA, theOutput.c );
*/  
  
  yy_delete_buffer(str_buffer);

  return err;
}



